#รูปแบบปกติถ้าใช้ database อันเดียว 
#จากการทดสอบใช้คู่กับแบบ multi-datasoure ยุ่งยาก เพราะถ้ามีการสร้าง Bean JdbcTemplate ตัวนั้นจะเป็น primary แทน defalut ของ spring
#spring.datasource.url=jdbc:mariadb://localhost:3306/spring_jdbc_api_multidb_db1
#....

##primary db (ใช้พารามิเตอร์ Hikari โดยตรง)
spring.datasource1.pool-name=mydb-1
spring.datasource1.jdbc-url=jdbc:mariadb://localhost:3306/spring_jdbc_api_multidb_db1
spring.datasource1.username=root
spring.datasource1.password=a1234
spring.datasource1.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource1.maximum-pool-size=3
spring.datasource1.minimum-idle=2
spring.datasource1.connection-timeout=30000

##test db2
spring.datasource2.pool-name=mydb-2
spring.datasource2.jdbc-url=jdbc:mariadb://localhost:3306/spring_jdbc_api_multidb_db2
spring.datasource2.username=root
spring.datasource2.password=a1234
spring.datasource2.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource2.maximum-pool-size=4
spring.datasource2.minimum-idle=2
spring.datasource2.connection-timeout=30000

#ให้ Spring Boot รัน script ใน src/main/resources/ ชื่อ schema.sql -> data.sql ตามลำดับ
#spring.sql.init.mode=always

